# Generated by Django 5.0.2 on 2024-02-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('sports', 'Sports')], max_length=100),
        ),
        migrations.AlterField(
            model_name='languagearticle',
            name='language',
            field=models.CharField(choices=[('tamil', 'Tamil'), ('hindi', 'Hindi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='languagearticlecontent',
            name='language',
            field=models.CharField(choices=[('tamil', 'Tamil'), ('hindi', 'Hindi')], max_length=10),
        ),
    ]
