# Generated by Django 5.0.2 on 2024-02-11 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.article'),
        ),
    ]
