# Generated by Django 5.0.2 on 2024-02-12 00:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_languagearticle_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique_for_date='publish_date'),
            preserve_default=False,
        ),
    ]
