# Generated by Django 5.0.2 on 2024-02-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
