# Generated by Django 5.0.2 on 2024-02-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_jobopening_alter_article_category_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='compensation',
            field=models.CharField(max_length=200),
        ),
    ]
